# Config file for automatic testing at travis-ci.org

language: python
python: 2.7
env:
    - TOX_ENV=docs
    - TOX_ENV=flake8
    - TOX_ENV=pypy 
    - TOX_ENV=pypy3
    - TOX_ENV=py27 
    - TOX_ENV=py33 
    - TOX_ENV=py34 

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r tests/requirements.txt
    - pip install -e .
    - pip install tox
    - pip install coveralls

script:
    - tox -e $TOX_ENV
    - py.test

after_success:
    - coveralls

notifications:
  email:
    on_success: never
    on_failure: change

